### PR TITLE
Add UI for status on ci.freedomdox.org and new GoCD conf

### PR DESCRIPTION
**Pull request by lispyclouds**
This is the UI for https://ci.freedombox.org

### CODE REVIEW

**Comment by lispyclouds** [comment]
This is the code is the UI for https://ci.freedombox.org

**Comment by jvalleroy** [comment]
Just wondering, would it make sense to create a new repository for the CI-related things? It seems to be more or less independent of freedom-maker.

**Comment by SunilMohanAdapa** [comment]
@jvalleroy , ci.freedombox.org will be a very simple thing which is almost already completed.  If it gets any bigger we can split it out.  Separate repository will be forgotten easily especially with the bug list. Shall we merge this into the project for now?

**Comment by SunilMohanAdapa** [comment]
This looks good for merging, by the way.

**Comment by SunilMohanAdapa** [comment]
On an second thought, @lispyclouds and I discussed the potential problems with licenses of jquery etc. when we are packaging freedom-maker due to this commit.  We will create a new repository called `infrastructure` and move all the ci stuff there.

@lispyclouds , closing this pull request.  Please commit there directly.

**Comment by lispyclouds** [comment]
Moved to https://github.com/freedombox/infrastructure

**Pull request closed without merging**
