### PR TITLE
Use xz for compression and misc

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
This pull request does the following:

- Use xz for compression offering significantly better compression.
- Build only once for i386 and amd64 targets and reuse for Qemu and VirtualBox images
- Fix issue with signing VirtualBox and Qemu targets.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
Added a small missing change for a20-olinuxino-micro.

**Comment by jvalleroy** [comment]
I get this error:
```
xz: build/freedombox-unstable-free_2015-12-14_all-i386.img.xz: Cannot set the file group: Operation not permitted
```
But in the build folder, I can see the .img file (owned by root), and the .img.xz file (owned by normal user).

Maybe just a permissions issue, but any idea how to resolve it?

**Comment by SunilMohanAdapa** [comment]
On 12/14/2015 06:57 PM, James Valleroy wrote:
> I get this error:
> 
> |xz: build/freedombox-unstable-free_2015-12-14_all-i386.img.xz: Cannot
> set the file group: Operation not permitted |
> 
> But in the build folder, I can see the .img file (owned by root), and
> the .img.xz file (owned by normal user).
> 
> Maybe just a permissions issue, but any idea how to resolve it?
> 

Did you run the xz command as regular user instead of root?  If normally
run using 'sudo make', I don't think you will see this.

-- 
Sunil

**Comment by jvalleroy** [comment]
Yes, that fixed it. I was in the habit of running without sudo (I guess the build script calls sudo where needed).

I've rebased and pushed these commits.

**Pull request closed without merging**
