### PR TITLE
Move hostname to 127.0.1.1 line of /etc/hosts.

### PR DESCRIPTION
**Pull request by jvalleroy**
This fixes the issue with setting domain name in Plinth: https://github.com/freedombox/Plinth/issues/262

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
I have reservations about using /etc/hosts for storing our domain name.

However, this patch is consistent with what we are doing so far and I have tested it to work as expected by building a new image.  /etc/hosts in the new image is expected.  Plinth after first boot shows empty domain as expected and then it reflects the proper domain name set in the configuration.  The Names modules shows the properly set domain name too.

**Comment by diederikdehaas** [comment]
AFAIK the IPv4 part of `/etc/hosts` should be (and is when you freshly install a Debian system):
```
127.0.0.1     localhost
127.0.1.1     <machine-name>.<domain-name>     <machine-name>
```
So I'm quite sure this PR does the correct thing.
(and is also what we do in the [Raspbian Netinstaller](https://github.com/debian-pi/raspbian-ua-netinst/))

**Comment by SunilMohanAdapa** [comment]
Forgot to mention that I have actually merged the patch.

**Comment by diederikdehaas** [comment]
I know. 
My response was because of your _reservations about using /etc/hosts for storing our domain name_.

**Comment by SunilMohanAdapa** [comment]
My reservations were based on larger requirements to manage multiple domains, service records etc. using a proper DNS server and using that as the conclusive list of domains.  Then, perhaps, we won't need a precise /etc/hosts.

Also, one of us should take the time and report this as a proper issue in `vmdebootstrap`.  It seems to be adding the hostname given on command line at the end of the 127.0.0.1 line.

**Pull request closed without merging**
