### PR TITLE
Verify raspberry pi blob script download

### PR DESCRIPTION
**Pull request by bashrc**
This verifies the rpi-update script which gets downloaded in order to shut down one possible avenue for nefariousness when creating an image which potentially might be widely used. Possibly there may be other bad stuff within the rpi-update script itself, and it may be possible to request a specific firmware version which could then also be checked.

Aside from the general badness of proprietary blobs my intuition is that if any adversary is going to try to engage in "equipment interference" then the manner in which the blob (or other firmware) is obtained is a likely route, since this would then scale to however many copies of the resulting image are subsequently made.

### CODE REVIEW

**Comment by jvalleroy** [comment]
I've rebased and pushed this change, with 1 small fix.

**Comment by SunilMohanAdapa** [comment]
We have keep a watch on the upstream changes and keep updating freedom-maker to use the newer version.  I guess we will do that.  But, not fun :)

**Comment by bashrc** [comment]
Not fun, but if I were a blackhat then adding an extra payload to a proprietary blob installed on every Rpi system would be exactly the sort of thing I'd try doing.

**Comment by SunilMohanAdapa** [comment]
On 01/21/2016 08:12 PM, Bob Mottram wrote:
> Not fun, but if I were a blackhat then adding an extra payload to a
> proprietary blob installed on every Rpi system would be exactly the sort
> of thing I'd try doing.

My comment was not on whether we should do the verification, but only on
the method of verification.

There are also limits to this implementation:

- The script updates itself before performing actual work and then the
check that we are doing is no longer applicable.

- The script does not contain the firmware but fetches the firmware from
elsewhere using a similar download mechanism without verification.

-- 
Sunil

**Comment by jvalleroy** [comment]
Looks like we can set UPDATE_SELF=0, and specify the git commit hash for the firmware.

**Comment by bashrc** [comment]
Another option might be to turn the firmware into a package which can be signed as part of a web of trust and exist in some non-free repo, then be installed in the conventional manner for debian. The main point is to avoid situations where there could be unauthorised modifications to an opaque blob which nobody is going to inspect closely.

**Pull request closed without merging**
