### PR TITLE
RFC: Use flask-kernel instead of custom scripts

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
This patch is not ready for merge yet.  It has not been tested well.

The idea is to use flash-kernel instead of custom scripts.  Whatever, was the state of flash-kernel, it seems okay now for being able to handle operations from inside chroot.  I have built a beagebone image with this patch and the output image contains /boot partition similar to how flash-kernel performs after a dist-upgrade happens in an image built by the earlier mechanism.  This gives me confidence that this new image should just fine on a BeagleBone.

I will build Cubietruck image and test it as representative of A20 processor based boards. I would appreciate it if someone can test BeagleBone Black and Dreamplug images with this patch.

### CODE REVIEW

**Comment by jvalleroy** [comment]
I tried testing on BBB, and ran into some issues:
1) If I just power on the device, it boots from the internal eMMC:
```
U-Boot SPL 2014.04-00014-g47880f5 (Apr 22 2014 - 13:23:54)
reading args
spl_load_image_fat_os: error reading image args, err - -1
reading u-boot.img
reading u-boot.img


U-Boot 2014.04-00014-g47880f5 (Apr 22 2014 - 13:23:54)

I2C:   ready
DRAM:  512 MiB
NAND:  0 MiB
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
*** Warning - readenv() failed, using default environment

Net:   <ethaddr> not set. Validating first E-fuse MAC
cpsw, usb_ether
Hit any key to stop autoboot:  1  0 
gpio: pin 53 (gpio 53) value is 1
mmc0 is current device
gpio: pin 54 (gpio 54) value is 1
SD/MMC found on device 0
** File not found uEnv.txt **
Checking if uenvcmd is set ...

uenvcmd was not defined in uEnv.txt ...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
mmc1(part 0) is current device
gpio: pin 54 (gpio 54) value is 1
SD/MMC found on device 1
reading uEnv.txt
1430 bytes read in 5 ms (279.3 KiB/s)
gpio: pin 55 (gpio 55) value is 1
Loaded environment from uEnv.txt
Importing environment from mmc ...
Checking if uenvcmd is set ...
gpio: pin 56 (gpio 56) value is 1
Running uenvcmd ...
reading zImage
3717760 bytes read in 207 ms (17.1 MiB/s)
reading initrd.img
2868973 bytes read in 161 ms (17 MiB/s)
reading /dtbs/am335x-boneblack.dtb
25080 bytes read in 9 ms (2.7 MiB/s)
Kernel image @ 0x82000000 [ 0x000000 - 0x38ba80 ]
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Using Device Tree in place at 88000000, end 880091f7

Starting kernel ...

Uncompressing Linux... done, booting the kernel.
[    0.382668] omap2_mbox_probe: platform not supported
[    0.549270] tps65217-bl tps65217-bl: no platform data provided
[    0.610686] bone-capemgr bone_capemgr.9: slot #0: No cape found
[    0.647793] bone-capemgr bone_capemgr.9: slot #1: No cape found
[    0.684901] bone-capemgr bone_capemgr.9: slot #2: No cape found
[    0.722010] bone-capemgr bone_capemgr.9: slot #3: No cape found
[    0.738170] bone-capemgr bone_capemgr.9: slot #6: BB-BONELT-HDMIN conflict P8.45 (#5:BB-BONELT-HDMI)
[    0.747794] bone-capemgr bone_capemgr.9: slot #6: Failed verification
[    0.754542] bone-capemgr bone_capemgr.9: loader: failed to load slot-6 BB-BONELT-HDMIN:00A0 (prio 2)
[    0.771020] omap_hsmmc mmc.5: of_parse_phandle_with_args of 'reset' failed
[    0.833622] pinctrl-single 44e10800.pinmux: pin 44e10854 already requested by 44e10800.pinmux; cannot claim for gpio-leds.8
[    0.845302] pinctrl-single 44e10800.pinmux: pin-21 (gpio-leds.8) status -22
[    0.852596] pinctrl-single 44e10800.pinmux: could not request pin 21 on device pinctrl-single
Loading, please wait...
Scanning for Btrfs filesystems
systemd-fsck[210]: rootfs: clean, 77142/230144 files, 383582/919296 blocks

Debian GNU/Linux 7 beaglebone ttyO0

default username:password is [debian:temppwd]

Support/FAQ: http://elinux.org/Beagleboard:BeagleBoneBlack_Debian

The IP Address for usb0 is: 192.168.7.2
beaglebone login:
```

2) If I hold S2, it will try to boot from the microSD. But it hangs at "Starting kernel ...". I also checked the microSD card and there is no first-run log.
```
U-Boot SPL 2016.01+dfsg1-2 (Feb 09 2016 - 04:14:04)
Trying to boot from MMC
MMC: block number 0x100 exceeds max(0x0)
MMC: block number 0x200 exceeds max(0x0)
*** Error - No Valid Environment Area found
*** Warning - bad CRC, using default environment




U-Boot 2016.01+dfsg1-2 (Feb 09 2016 - 04:14:04 +0000)


       Watchdog enabled

I2C:   ready

DRAM:  512 MiB

MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1

*** Warning - bad CRC, using default environment


Net:   <ethaddr> not set. Validating first E-fuse MAC

cpsw

Hit any key to stop autoboot:  2  1  0 

switch to partitions #0, OK

mmc0 is current device

Scanning mmc 0:1...

Found U-Boot script /boot.scr

1577 bytes read in 17 ms (89.8 KiB/s)

## Executing script at 80000000

3416656 bytes read in 214 ms (15.2 MiB/s)

31540 bytes read in 27 ms (1.1 MiB/s)

14500865 bytes read in 857 ms (16.1 MiB/s)

Booting Debian 4.3.0-1-armmp from mmc 0:1...

Kernel image @ 0x82000000 [ 0x000000 - 0x342250 ]

## Flattened Device Tree blob at 88000000

   Booting using the fdt blob at 0x88000000

   Loading Ramdisk to 8f22b000, end 8ffff401 ... OK

   Loading Device Tree to 8f220000, end 8f22ab33 ... OK


Starting kernel ...
```

**Comment by jvalleroy** [comment]
I get an error when building the Dreamplug image:
```
Creating disk image
Creating partitions
Using bootsize 122mib: 128000000 bytes
Creating filesystem btrfs
Mounting /dev/mapper/loop0p2 on /tmp/tmpl0miNw
Creating filesystem vfat
Mounting /dev/mapper/loop0p1 on /tmp/tmpl0miNw/boot/
Debootstrapping unstable [armel]
Setting up binfmt handler
Running debootstrap second stage
Locking root password
Removing udev persistent cd and net rules
Setting up networking
Running customize script /home/jvalleroy/fbx/freedom-maker/freedommaker/freedombox-customize
Updating the initramfs
EEEK! Something bad happened...
command failed: ['chroot', '/tmp/tmpl0miNw', 'usr/sbin/update-initramfs', '-u']
update-initramfs: Generating /boot/initrd.img-4.3.0-1-kirkwood
Warning: couldn't identify filesystem type for fsck hook, ignoring.

/bin/ln: failed to create hard link '/boot/initrd.img-4.3.0-1-kirkwood.dpkg-bak' => '/boot/initrd.img-4.3.0-1-kirkwood': Operation not permitted
UUID 9634526e-8b08-4f02-a013-fd10affd0323 doesn't exist in /dev/disk/by-uuid
Warning: root device /dev/disk/by-uuid/9634526e-8b08-4f02-a013-fd10affd0323 does not exist
DTB: kirkwood-dreamplug.dtb
Installing kirkwood-dreamplug.dtb into /boot/dtbs/4.3.0-1-kirkwood/kirkwood-dreamplug.dtb
Installing new kirkwood-dreamplug.dtb.
/bin/ln: failed to create symbolic link '/boot/dtb-4.3.0-1-kirkwood': Operation not permitted
run-parts: /etc/initramfs/post-update.d//flash-kernel exited with return code 1
```

**Comment by SunilMohanAdapa** [comment]
I have tested on Cubietruck.  I ran into an issue with vmdebootstrap and fixed it.  Other than that, the image booted just fine.  I believe that based on this, this patch will work for all A20 based devices.

For BeagleBone Black, I believe we are seeing the same issue as after kernel upgrades.  Once that issue is fixed, BBB would also work with this patch.

I will read about Dreamplug's boot process to see if really need vfat filesystem for booting.

**Comment by SunilMohanAdapa** [comment]
Most images are now using flash-kernel: A20 based devices and beaglebone.  Raspberry Pi images and Dreamplug remain.  Both can actually use flash-kernel but require /boot partition to be ext2 instead of fat32 for kernel upgrades to work.  I will create tasks for getting there and remaining work for using the flash-kernel script.

Closing because most changes got committed and remaining will live on as separate tasks.

**Comment by diederikdehaas** [comment]
> Raspberry Pi images and Dreamplug remain. Both can actually use flash-kernel but require /boot partition to be ext2 instead of fat32 for kernel upgrades to work.

Note that the **firmware** files for the Raspberry Pi **MUST** be on fat32 and that fat32 partition must be the first partition on the disk. This is hardwired into the GPU, which is the first thing that boots and starts up the CPUs.

But it indeed can be done: http://sjoerd.luon.net/posts/2015/02/debian-jessie-on-rpi2/

**Pull request closed without merging**
