### PR TITLE
Move security access config to freedom-maker.

### PR DESCRIPTION
**Pull request by jvalleroy**
As suggested during the last progress call, consider moving this configuration here. This is to avoid applying this config to existing Debian installs when freedombox-setup is run. There are a few reasons for this:
- Avoid locking out existing Debian users.
- This config prevents some display managers from starting, which may be a surprise for the user.
- We will want to run the freedombox-setup script automatically when f-s is installed. But /etc/security/access.conf is a conffile owned by libpam-modules. We definitely can't trigger automatic modifications to this file, per Debian policy.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
During the progress call, I was suggesting that we could separate out this kind of scripts into a `freedombox-security` (could be built from `freedom-setup` source package). This package may not be installed by Debian users or from Debian installer, but we will recommend it.

With this approach, most of the stuff that goes into the images will be part of Debian archive.  We can also write upgrade scripts into this package's `postinst`. What are your thoughts on this approach?

**Comment by jvalleroy** [comment]
@SunilMohanAdapa Ok, that sounds like a good approach. It's better to have it in some package so we can handle upgrades. I'll close this PR.

**Comment by jvalleroy** [comment]
@SunilMohanAdapa Another option, we could have a Plinth "security" module that handles this optional configuration, and use the setup mechanism to handle upgrades. I think this would be much easier than creating a new package. What do you think?

**Comment by SunilMohanAdapa** [comment]
@jvalleroy , that sounds good.

There is the question of whether this setting will be enabled by default. On one hand, allowing other users to login too much of a risk to not enable by default.  On the other hand, people installing via d-i or using freedombox-setup will face problems.

**Pull request closed without merging**
