### PR TITLE
Add banana-pro target

### PR DESCRIPTION
**Pull request by jvalleroy**
I have tested on the Banana Pro, confirmed that I could access Plinth and create a user.

### CODE REVIEW

**Comment by JosephKiranBabu** [comment]
@jvalleroy Will this image also work on a Banana Pi?

**Comment by jvalleroy** [comment]
@JosephKiranBabu I think not. Banana Pi has a separate DTB and u-boot. It should be easy to add as another target though.

**Comment by SunilMohanAdapa** [comment]
Merged with minor change to documentation. I was able to successfully build the image.

**Comment by JosephKiranBabu** [comment]
@SunilMohanAdapa Can this be closed?

**Pull request closed without merging**
